<a href="https://colab.research.google.com/github/Farzam1372/Farzam1372/blob/main/missing_data_set_falcon9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%matplotlib inline

import numpy as np
import pandas as pd


from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.dummy import DummyClassifier

from matplotlib import pyplot as plt
import seaborn as sns

In [ ]:
df_missing=pd.read_excel('/content/sample_data/missing_dataset_falcon9.xlsx')

In [ ]:
df_missing

,FlightNumber,Date,BoosterVersion,PayloadMass,Orbit,LaunchSite,Outcome,Flights,GridFins,Reused,Legs,LandingPad,Block,ReusedCount,Serial,Longitude,Latitude,Class
0,1,2010-06-04,Falcon 9,6104.959412,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1,0,B0003,-80.577366,28.561857,0
1,2,2012-05-22,Falcon 9,525.000000,LEO,CCAFS SLC 40,None None,1,False,False,False,NaN,1,0,B0005,-80.577366,28.561857,0
2,3,2013-03-01,Falcon 9,677.000000,ISS,CCAFS SLC 40,None None,1,False,False,False,NaN,1,0,B0007,-80.577366,28.561857,0
3,4,2013-09-29,Falcon 9,NaN,PO,VAFB SLC 4E,False Ocean,1,False,False,False,NaN,1,0,B1003,-120.610829,34.632093,0
4,5,2013-12-03,Falcon 9,3170.000000,GTO,NaN,None None,1,False,False,False,NaN,1,0,B1004,-80.577366,28.561857,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,86,2020-09-03,Falcon 9,15400.000000,VLEO,KSC LC 39A,True ASDS,2,True,True,True,5e9e3032383ecb6bb234e7ca,5,2,B1060,-80.603956,28.608058,1
86,87,2020-10-06,Falcon 9,15400.000000,VLEO,KSC LC 39A,True ASDS,3,True,True,True,5e9e3032383ecb6bb234e7ca,5,2,B1058,-80.603956,28.608058,1
87,88,2020-10-18,Falcon 9,15400.000000,VLEO,KSC LC 39A,True ASDS,6,True,True,True,5e9e3032383ecb6bb234e7ca,5,5,B1051,-80.603956,28.608058,1
88,89,2020-10-24,Falcon 9,15400.000000,VLEO,CCAFS SLC 40,True ASDS,3,True,True,True,5e9e3033383ecbb9e534e7cc,5,2,B1060,-80.577366,28.561857,1
89,90,2020-11-05,Falcon 9,3681.000000,MEO,CCAFS SLC 40,True ASDS,1,True,False,True,5e9e3032383ecb6bb234e7ca,5,0,B1062,-80.577366,28.561857,1

In [ ]:
df_missing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   FlightNumber    90 non-null     int64
 1   Date            90 non-null     datetime64[ns]
 2   BoosterVersion  90 non-null     object
 3   PayloadMass     81 non-null     float64
 4   Orbit           90 non-null     object
 5   LaunchSite      86 non-null     object
 6   Outcome         90 non-null     object
 7   Flights         90 non-null     int64
 8   GridFins        90 non-null     bool
 9   Reused          90 non-null     bool
 10  Legs            90 non-null     bool
 11  LandingPad      64 non-null     object
 12  Block           90 non-null     int64
 13  ReusedCount     90 non-null     int64
 14  Serial          90 non-null     object
 15  Longitude       90 non-null     float64
 16  Latitude        90 non-null     float64
 17  Class           90 non-null     int64
dtypes: bool(3), datetime64[ns](1), float64(3), int64(5), object(6)
memory usage: 10.9+ KB

In [ ]:
payload_mean=df_missing['PayloadMass'].mean()
payload_mean

6379.7368845315905

In [ ]:
df_missing['PayloadMass']

0      6104.959412
1       525.000000
2       677.000000
3              NaN
4      3170.000000
          ...
85    15400.000000
86    15400.000000
87    15400.000000
88    15400.000000
89     3681.000000
Name: PayloadMass, Length: 90, dtype: float64

In [ ]:
df_missing['PayloadMass'] = df_missing['PayloadMass'].replace(np.nan, payload_mean)
df_missing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   FlightNumber    90 non-null     int64
 1   Date            90 non-null     datetime64[ns]
 2   BoosterVersion  90 non-null     object
 3   PayloadMass     90 non-null     float64
 4   Orbit           90 non-null     object
 5   LaunchSite      86 non-null     object
 6   Outcome         90 non-null     object
 7   Flights         90 non-null     int64
 8   GridFins        90 non-null     bool
 9   Reused          90 non-null     bool
 10  Legs            90 non-null     bool
 11  LandingPad      64 non-null     object
 12  Block           90 non-null     int64
 13  ReusedCount     90 non-null     int64
 14  Serial          90 non-null     object
 15  Longitude       90 non-null     float64
 16  Latitude        90 non-null     float64
 17  Class           90 non-null     int64
dtypes: bool(3), datetime64[ns](1), float64(3), int64(5), object(6)
memory usage: 10.9+ KB

In [ ]:
df_missing['LaunchSite'].value_counts()

CCAFS SLC 40    53
KSC LC 39A      20
VAFB SLC 4E     13
Name: LaunchSite, dtype: int64

In [ ]:
df_missing['LaunchSite'] = df_missing['LaunchSite'].replace(np.nan, 'CCAFS SLC 40')

In [ ]:
df_missing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   FlightNumber    90 non-null     int64
 1   Date            90 non-null     datetime64[ns]
 2   BoosterVersion  90 non-null     object
 3   PayloadMass     90 non-null     float64
 4   Orbit           90 non-null     object
 5   LaunchSite      90 non-null     object
 6   Outcome         90 non-null     object
 7   Flights         90 non-null     int64
 8   GridFins        90 non-null     bool
 9   Reused          90 non-null     bool
 10  Legs            90 non-null     bool
 11  LandingPad      64 non-null     object
 12  Block           90 non-null     int64
 13  ReusedCount     90 non-null     int64
 14  Serial          90 non-null     object
 15  Longitude       90 non-null     float64
 16  Latitude        90 non-null     float64
 17  Class           90 non-null     int64
dtypes: bool(3), datetime64[ns](1), float64(3), int64(5), object(6)
memory usage: 10.9+ KB

In [ ]:
df_missing['LandingPad'].value_counts()

5e9e3032383ecb6bb234e7ca    35
5e9e3032383ecb267a34e7c7    13
5e9e3033383ecbb9e534e7cc    12
5e9e3032383ecb761634e7cb     2
5e9e3032383ecb554034e7c9     2
Name: LandingPad, dtype: int64

In [ ]:
df_landingpad = df_missing[df_missing['LandingPad']=='5e9e3032383ecb6bb234e7ca']
set(df_landingpad['Orbit'])

{'GTO', 'HEO', 'ISS', 'MEO', 'VLEO'}

In [ ]:
df_missing[['LandingPad', 'Orbit']]

                  LandingPad Orbit
0                        NaN   LEO
1                        NaN   LEO
2                        NaN   ISS
3                        NaN    PO
4                        NaN   GTO
..                       ...   ...
85  5e9e3032383ecb6bb234e7ca  VLEO
86  5e9e3032383ecb6bb234e7ca  VLEO
87  5e9e3032383ecb6bb234e7ca  VLEO
88  5e9e3033383ecbb9e534e7cc  VLEO
89  5e9e3032383ecb6bb234e7ca   MEO

[90 rows x 2 columns]

In [ ]:
df_missing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   FlightNumber    90 non-null     int64
 1   Date            90 non-null     datetime64[ns]
 2   BoosterVersion  90 non-null     object
 3   PayloadMass     90 non-null     float64
 4   Orbit           90 non-null     object
 5   LaunchSite      90 non-null     object
 6   Outcome         90 non-null     object
 7   Flights         90 non-null     int64
 8   GridFins        90 non-null     bool
 9   Reused          90 non-null     bool
 10  Legs            90 non-null     bool
 11  LandingPad      64 non-null     object
 12  Block           90 non-null     int64
 13  ReusedCount     90 non-null     int64
 14  Serial          90 non-null     object
 15  Longitude       90 non-null     float64
 16  Latitude        90 non-null     float64
 17  Class           90 non-null     int64
dtypes: bool(3), datetime64[ns](1), float64(3), int64(5), object(6)
memory usage: 10.9+ KB

In [ ]:
df_missing['LaunchSite']

0     CCAFS SLC 40
1     CCAFS SLC 40
2     CCAFS SLC 40
3      VAFB SLC 4E
4     CCAFS SLC 40
          ...
85      KSC LC 39A
86      KSC LC 39A
87      KSC LC 39A
88    CCAFS SLC 40
89    CCAFS SLC 40
Name: LaunchSite, Length: 90, dtype: object

In [ ]:
dummy_1 = pd.get_dummies(df_missing['LaunchSite'])
dummy_1

    CCAFS SLC 40  KSC LC 39A  VAFB SLC 4E
0              1           0            0
1              1           0            0
2              1           0            0
3              0           0            1
4              1           0            0
..           ...         ...          ...
85             0           1            0
86             0           1            0
87             0           1            0
88             1           0            0
89             1           0            0

[90 rows x 3 columns]

In [ ]:
set(df_missing['LaunchSite'])

{'CCAFS SLC 40', 'KSC LC 39A', 'VAFB SLC 4E'}

In [ ]:
dummy_2 = pd.get_dummies(df_missing['LandingPad'])
dummy_2[10:20]

,5e9e3032383ecb267a34e7c7,5e9e3032383ecb554034e7c9,5e9e3032383ecb6bb234e7ca,5e9e3032383ecb761634e7cb,5e9e3033383ecbb9e534e7cc
10,0,0,0,0,0
11,0,0,0,1,0
12,0,0,0,0,0
13,0,0,0,1,0
14,0,0,0,0,0
15,0,0,1,0,0
16,1,0,0,0,0
17,0,0,0,0,1
18,0,0,1,0,0
19,0,0,1,0,0

In [ ]:
df_dummy = pd.get_dummies(df_missing[['LandingPad', 'Orbit', 'Serial', 'Outcome', 'LaunchSite']])

In [ ]:
df_dummy

,LandingPad_5e9e3032383ecb267a34e7c7,LandingPad_5e9e3032383ecb554034e7c9,LandingPad_5e9e3032383ecb6bb234e7ca,LandingPad_5e9e3032383ecb761634e7cb,LandingPad_5e9e3033383ecbb9e534e7cc,Orbit_ES-L1,Orbit_GEO,Orbit_GTO,Orbit_HEO,Orbit_ISS,...,Outcome_False Ocean,Outcome_False RTLS,Outcome_None ASDS,Outcome_None None,Outcome_True ASDS,Outcome_True Ocean,Outcome_True RTLS,LaunchSite_CCAFS SLC 40,LaunchSite_KSC LC 39A,LaunchSite_VAFB SLC 4E
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
2,0,0,0,0,0,0,0,0,0,1,...,0,0,0,1,0,0,0,1,0,0
3,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
4,0,0,0,0,0,0,0,1,0,0,...,0,0,0,1,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
86,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
87,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
88,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0
89,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0

In [ ]:
df_missing['GridFins'] = df_missing['GridFins'].astype(int)
df_missing['Reused'] = df_missing['Reused'].astype(int)
df_missing['Legs'] = df_missing['Legs'].astype(int)

In [ ]:
df_missing

,FlightNumber,Date,BoosterVersion,PayloadMass,Orbit,LaunchSite,Outcome,Flights,GridFins,Reused,Legs,LandingPad,Block,ReusedCount,Serial,Longitude,Latitude,Class
0,1,2010-06-04,Falcon 9,6104.959412,LEO,CCAFS SLC 40,None None,1,0,0,0,NaN,1,0,B0003,-80.577366,28.561857,0
1,2,2012-05-22,Falcon 9,525.000000,LEO,CCAFS SLC 40,None None,1,0,0,0,NaN,1,0,B0005,-80.577366,28.561857,0
2,3,2013-03-01,Falcon 9,677.000000,ISS,CCAFS SLC 40,None None,1,0,0,0,NaN,1,0,B0007,-80.577366,28.561857,0
3,4,2013-09-29,Falcon 9,6379.736885,PO,VAFB SLC 4E,False Ocean,1,0,0,0,NaN,1,0,B1003,-120.610829,34.632093,0
4,5,2013-12-03,Falcon 9,3170.000000,GTO,CCAFS SLC 40,None None,1,0,0,0,NaN,1,0,B1004,-80.577366,28.561857,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,86,2020-09-03,Falcon 9,15400.000000,VLEO,KSC LC 39A,True ASDS,2,1,1,1,5e9e3032383ecb6bb234e7ca,5,2,B1060,-80.603956,28.608058,1
86,87,2020-10-06,Falcon 9,15400.000000,VLEO,KSC LC 39A,True ASDS,3,1,1,1,5e9e3032383ecb6bb234e7ca,5,2,B1058,-80.603956,28.608058,1
87,88,2020-10-18,Falcon 9,15400.000000,VLEO,KSC LC 39A,True ASDS,6,1,1,1,5e9e3032383ecb6bb234e7ca,5,5,B1051,-80.603956,28.608058,1
88,89,2020-10-24,Falcon 9,15400.000000,VLEO,CCAFS SLC 40,True ASDS,3,1,1,1,5e9e3033383ecbb9e534e7cc,5,2,B1060,-80.577366,28.561857,1
89,90,2020-11-05,Falcon 9,3681.000000,MEO,CCAFS SLC 40,True ASDS,1,1,0,1,5e9e3032383ecb6bb234e7ca,5,0,B1062,-80.577366,28.561857,1

In [ ]:
df = df_missing.drop(['LandingPad', 'Orbit', 'Serial', 'Outcome', 'LaunchSite'], axis=1)
df = pd.concat([df, df_dummy], axis=1)
df

,FlightNumber,Date,BoosterVersion,PayloadMass,Flights,GridFins,Reused,Legs,Block,ReusedCount,...,Outcome_False Ocean,Outcome_False RTLS,Outcome_None ASDS,Outcome_None None,Outcome_True ASDS,Outcome_True Ocean,Outcome_True RTLS,LaunchSite_CCAFS SLC 40,LaunchSite_KSC LC 39A,LaunchSite_VAFB SLC 4E
0,1,2010-06-04,Falcon 9,6104.959412,1,0,0,0,1,0,...,0,0,0,1,0,0,0,1,0,0
1,2,2012-05-22,Falcon 9,525.000000,1,0,0,0,1,0,...,0,0,0,1,0,0,0,1,0,0
2,3,2013-03-01,Falcon 9,677.000000,1,0,0,0,1,0,...,0,0,0,1,0,0,0,1,0,0
3,4,2013-09-29,Falcon 9,6379.736885,1,0,0,0,1,0,...,1,0,0,0,0,0,0,0,0,1
4,5,2013-12-03,Falcon 9,3170.000000,1,0,0,0,1,0,...,0,0,0,1,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,86,2020-09-03,Falcon 9,15400.000000,2,1,1,1,5,2,...,0,0,0,0,1,0,0,0,1,0
86,87,2020-10-06,Falcon 9,15400.000000,3,1,1,1,5,2,...,0,0,0,0,1,0,0,0,1,0
87,88,2020-10-18,Falcon 9,15400.000000,6,1,1,1,5,5,...,0,0,0,0,1,0,0,0,1,0
88,89,2020-10-24,Falcon 9,15400.000000,3,1,1,1,5,2,...,0,0,0,0,1,0,0,1,0,0
89,90,2020-11-05,Falcon 9,3681.000000,1,1,0,1,5,0,...,0,0,0,0,1,0,0,1,0,0

In [ ]:
df.to_csv('C:\\Users\FARZAM\Desktop\data science road map\preprocessed_dataset.csv')

In [ ]:

df.to_csv('C:\\Users\\FARZAM\\Desktop\\data science road map\\preprocessed_dataset.csv', index=False)